import jsPDF from "jspdf";

const formatValue = (value) => {
  if (value == null || value === "") return "Not available";
  if (typeof value === "number") {
    return Number.isInteger(value) ? String(value) : value.toFixed(1);
  }
  return String(value);
};

const cleanText = (value) =>
  String(value ?? "")
    .replace(/^#{1,6}\s*/gm, "")
    .replace(/^\s*[-*]\s*/gm, "")
    .replace(/\*\*/g, "")
    .replace(/\u2022/g, "-")
    .trim();

export function exportReportPdf({
  title,
  subtitle,
  badge,
  generatedAt,
  footerText = "Generated by Lilycrest Maintenance Management System",
  filename,
  kpis = [],
  sections = [],
}) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  const navy = [15, 39, 66];
  const gold = [218, 151, 47];
  const slate = [71, 85, 105];
  let y = 43;

  const ensureSpace = (needed = 12) => {
    if (y + needed <= pageHeight - margin) return;
    doc.addPage();
    y = margin;
  };

  const toLines = (text, width = contentWidth) => doc.splitTextToSize(cleanText(text), width);

  const writeLines = (lines, { x = margin, lineHeight = 4.5, font = "normal", size = 9, color } = {}) => {
    const normalizedLines = Array.isArray(lines) ? lines : [cleanText(lines)];
    if (normalizedLines.length === 0) return;
    ensureSpace(normalizedLines.length * lineHeight + 1);
    doc.setFont("helvetica", font);
    doc.setFontSize(size);
    if (color) doc.setTextColor(...color);
    doc.text(normalizedLines, x, y);
    doc.setTextColor(17, 24, 39);
    y += normalizedLines.length * lineHeight;
  };

  const drawHeader = () => {
    doc.setFillColor(...navy);
    doc.rect(0, 0, pageWidth, 34, "F");
    doc.setFillColor(...gold);
    doc.rect(0, 34, pageWidth, 1.4, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Lilycrest Residences / Lilycrest Dormitory", margin, 12);
    doc.setFontSize(17);
    doc.text(cleanText(title || "Maintenance Report"), margin, 22);

    if (badge) {
      doc.setFillColor(255, 247, 237);
      doc.roundedRect(pageWidth - margin - 50, 10, 50, 9, 2, 2, "F");
      doc.setTextColor(146, 64, 14);
      doc.setFontSize(8);
      doc.text(cleanText(badge).toUpperCase(), pageWidth - margin - 25, 16, { align: "center" });
    }

    doc.setTextColor(17, 24, 39);
  };

  const drawCard = (x, top, width, height) => {
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, top, width, height, 2, 2, "FD");
  };

  drawHeader();

  if (subtitle) {
    writeLines(toLines(subtitle), { size: 10, color: slate });
  }

  const generated = generatedAt ? new Date(generatedAt) : new Date();
  writeLines(
    `Generated: ${generated.toLocaleString("en-PH", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    })}`,
    { size: 9, color: slate },
  );
  y += 2;

  if (kpis.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...navy);
    doc.text("Summary", margin, y);
    y += 5;

    const colGap = 4;
    const colWidth = (contentWidth - colGap) / 2;
    kpis.forEach((item, index) => {
      if (index % 2 === 0) ensureSpace(18);
      const x = margin + (index % 2) * (colWidth + colGap);
      const top = y + Math.floor(index / 2) * 16;
      drawCard(x, top, colWidth, 13);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...slate);
      doc.text(cleanText(item.label), x + 3, top + 5);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(17, 24, 39);
      doc.text(cleanText(formatValue(item.value)), x + 3, top + 10);
    });
    y += Math.ceil(kpis.length / 2) * 16 + 4;
  }

  sections.forEach((section) => {
    ensureSpace(18);
    doc.setFillColor(...navy);
    doc.roundedRect(margin, y, contentWidth, 8, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(cleanText(section.title), margin + 3, y + 5.5);
    y += 11;
    doc.setTextColor(17, 24, 39);

    if (section.description) {
      writeLines(toLines(section.description), { size: 9, color: slate });
      y += 1;
    }

    const rows = Array.isArray(section.rows) && section.rows.length > 0
      ? section.rows
      : ["No rows available."];

    rows.forEach((row) => {
      const rowLines = toLines(row, contentWidth - 6);
      ensureSpace(rowLines.length * 4.5 + 5);
      doc.setDrawColor(226, 232, 240);
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(margin, y - 2.5, contentWidth, rowLines.length * 4.5 + 2, 1, 1, "FD");
      writeLines(rowLines, { x: margin + 3, size: 9, lineHeight: 4.5 });
      y += 1;
    });
  });

  const totalPages = doc.internal.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...slate);
    doc.text(`${footerText} - Page ${page} of ${totalPages}`, pageWidth / 2, pageHeight - 8, {
      align: "center",
    });
  }

  doc.save(filename || "maintenance-report.pdf");
}
