import mongoose from "mongoose";
import { ROOM_BRANCHES } from "../config/branches.js";

export const CONTRACT_STATUSES = Object.freeze([
  "draft", "incomplete", "ready_for_generation", "generated",
  "awaiting_signatures", "partially_signed", "signed",
  "awaiting_notarization", "notarized", "ready_for_publication",
  "published", "active", "expiring_soon", "expired", "renewal_pending",
  "renewed", "transfer_review_required", "terminated", "cancelled",
  "replaced", "archived", "voided", "rejected",
]);

const statusHistorySchema = new mongoose.Schema(
  {
    status: { type: String, enum: CONTRACT_STATUSES, required: true },
    changedAt: { type: Date, default: Date.now, required: true },
    changedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    reason: { type: String, trim: true, default: "" },
  },
  { _id: false },
);

const preparedDocumentSchema = new mongoose.Schema(
  {
    documentType: { type: String, enum: ["prepared"], default: "prepared" },
    version: { type: Number, required: true, min: 1 },
    storageProvider: {
      type: String,
      enum: ["local", "firebase-storage"],
      default: "local",
    },
    storageKey: { type: String, required: true },
    fileName: { type: String, required: true },
    fileHash: { type: String, required: true },
    fileSize: { type: Number, required: true, min: 1 },
    pageCount: { type: Number, required: true, min: 1 },
    generatedAt: { type: Date, required: true },
    generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    templateId: { type: String, required: true },
    templateVersion: { type: String, required: true },
    coordinateVersion: { type: String, required: true },
    reason: { type: String, default: "", trim: true },
    superseded: { type: Boolean, default: false },
    generationSnapshot: { type: mongoose.Schema.Types.Mixed, default: null },
    renderMetadata: { type: mongoose.Schema.Types.Mixed, default: null },
  },
  { _id: false },
);

const signedDocumentSchema = new mongoose.Schema(
  {
    version: { type: Number, required: true, min: 1 },
    storageKey: { type: String, required: true },
    fileName: { type: String, required: true },
    fileHash: { type: String, required: true },
    fileSize: { type: Number, required: true, min: 1 },
    mimeType: { type: String, required: true },
    uploadedAt: { type: Date, required: true },
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    preparedDocumentVersion: { type: Number, required: true, min: 1 },
    superseded: { type: Boolean, default: false },
    replacementReason: { type: String, default: "", trim: true },
    rejectionReason: { type: String, default: "", trim: true },
    rejectedAt: { type: Date, default: null },
    rejectedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    verifiedAt: { type: Date, default: null },
    verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    verificationNotes: { type: String, default: "", trim: true },
    verificationChecklist: { type: mongoose.Schema.Types.Mixed, default: null },
    notarialDetails: { type: mongoose.Schema.Types.Mixed, default: null },
  },
  { _id: false },
);

const finalDocumentSchema = new mongoose.Schema(
  {
    storageKey: { type: String, required: true, immutable: true },
    fileName: { type: String, required: true, immutable: true },
    fileHash: { type: String, required: true, immutable: true },
    fileSize: { type: Number, required: true, min: 1, immutable: true },
    mimeType: { type: String, required: true, immutable: true },
    pageCount: { type: Number, required: true, min: 1, immutable: true },
    sourceType: { type: String, enum: ["notarized"], required: true, immutable: true },
    sourceVersion: { type: Number, required: true, min: 1, immutable: true },
    sourceUploadedAt: { type: Date, required: true, immutable: true },
    sourceVerifiedAt: { type: Date, required: true, immutable: true },
    sourceVerifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, immutable: true },
    publishedAt: { type: Date, required: true, immutable: true },
    publishedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, immutable: true },
    tenantVisible: { type: Boolean, default: true, required: true, immutable: true },
  },
  { _id: false },
);

const contractSchema = new mongoose.Schema(
  {
    tenantId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    applicationId: { type: mongoose.Schema.Types.ObjectId, ref: "Reservation", default: null, index: true },
    reservationId: { type: mongoose.Schema.Types.ObjectId, ref: "Reservation", required: true, index: true },
    stayId: { type: mongoose.Schema.Types.ObjectId, ref: "Stay", default: null },
    roomId: { type: mongoose.Schema.Types.ObjectId, ref: "Room", required: true, index: true },
    branch: { type: String, enum: ROOM_BRANCHES, required: true, index: true },

    contractNumber: { type: String, required: true, immutable: true, unique: true },
    contractYear: { type: Number, required: true, immutable: true },
    contractSequence: { type: Number, required: true, immutable: true },
    version: { type: Number, default: 1, min: 1, immutable: true },
    duplicateOfContractId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Contract",
      default: null,
    },
    templateType: { type: String, trim: true, default: "" },
    roomType: { type: String, enum: ["private", "double-sharing", "quadruple-sharing"], required: true },
    leaseType: { type: String, enum: ["short_term", "long_term"], required: true },

    propertyName: { type: String, required: true, trim: true, immutable: true },
    propertyAddress: { type: String, required: true, trim: true, immutable: true },
    roomNumber: { type: String, required: true, trim: true, immutable: true },
    bedId: { type: String, default: "", trim: true, immutable: true },
    bedLabel: { type: String, default: "", trim: true, immutable: true },

    tenantLegalName: { type: String, default: "", trim: true, immutable: true },
    tenantAddress: { type: String, default: "", trim: true, immutable: true },
    tenantEmail: { type: String, default: "", trim: true, lowercase: true, immutable: true },
    tenantPhone: { type: String, default: "", trim: true, immutable: true },
    tenantNationality: { type: String, default: "", trim: true, immutable: true },
    tenantBirthDate: { type: Date, default: null, immutable: true },
    tenantAgeAtGeneration: { type: Number, default: null, min: 18, immutable: true },

    leaseStartDate: { type: Date, default: null, immutable: true },
    leaseEndDate: { type: Date, default: null, immutable: true },
    leaseDurationMonths: { type: Number, default: null, min: 1, immutable: true },

    regularMonthlyRate: { type: Number, default: null, min: 0 },
    discountPercentage: { type: Number, default: null, min: 0, max: 100 },
    discountType: { type: String, enum: ["percentage", "none"], default: "percentage" },
    discountAmount: { type: Number, default: null, min: 0 },
    approvedMonthlyRate: { type: Number, default: null, min: 0 },
    advanceRentAmount: { type: Number, default: null, min: 0 },
    securityDepositAmount: { type: Number, default: null, min: 0 },
    reservationFeeAmount: { type: Number, default: null, min: 0 },
    reservationFeeCreditAmount: { type: Number, default: null, min: 0 },
    pricingApprovalId: { type: mongoose.Schema.Types.ObjectId, ref: "Reservation", default: null },
    pricingApprovedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    pricingApprovedAt: { type: Date, default: null },
    pricingApprovalNotes: { type: String, default: "", trim: true },
    advanceCoverageStart: { type: Date, default: null, immutable: true },
    advanceCoverageEnd: { type: Date, default: null, immutable: true },
    executionDate: { type: Date, default: null },

    templateVersion: { type: String, default: null },
    legalContentVersion: { type: String, default: null },
    validatedGenerationData: { type: mongoose.Schema.Types.Mixed, default: null },
    lastValidatedAt: { type: Date, default: null },

    generatedStorageKey: { type: String, default: null },
    generatedFileName: { type: String, default: null },
    generatedFileHash: { type: String, default: null },
    generatedFileSize: { type: Number, default: null, min: 1 },
    generatedPageCount: { type: Number, default: null, min: 1 },
    generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    generatedVersion: { type: Number, default: 0, min: 0 },
    preparedDocuments: { type: [preparedDocumentSchema], default: [] },
    printedAt: { type: Date, default: null },
    printedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    tenantSignatureStatus: { type: String, enum: ["pending", "completed", "not_required"], default: "pending" },
    tenantSignedAt: { type: Date, default: null },
    tenantSignatureConfirmedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    lessorSignatureStatus: { type: String, enum: ["pending", "completed", "not_required"], default: "pending" },
    lessorSignedAt: { type: Date, default: null },
    lessorSignatureConfirmedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    witnessSignatureStatus: { type: String, enum: ["pending", "completed", "not_required"], default: "pending" },
    witnessSignedAt: { type: Date, default: null },
    witnessSignatureConfirmedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    signedStorageKey: { type: String, default: null },
    signedFileName: { type: String, default: null },
    signedFileHash: { type: String, default: null },
    signedFileSize: { type: Number, default: null, min: 1 },
    signedMimeType: { type: String, default: null },
    signedUploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    signedDocumentVersion: { type: Number, default: 0, min: 0 },
    signedDocuments: { type: [signedDocumentSchema], default: [] },
    signingVerifiedAt: { type: Date, default: null },
    signingVerifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    signingVerificationNotes: { type: String, default: "", trim: true },
    signingRejectionReason: { type: String, default: "", trim: true },
    notarizedFileName: { type: String, default: null },
    notarizedFileHash: { type: String, default: null },
    notarizedFileSize: { type: Number, default: null, min: 1 },
    notarizedMimeType: { type: String, default: null },
    notarizedUploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    notarizedDocumentVersion: { type: Number, default: 0, min: 0 },
    notarizedDocuments: { type: [signedDocumentSchema], default: [] },
    notarizationVerifiedAt: { type: Date, default: null },
    notarizationVerifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    notarizationVerificationNotes: { type: String, default: "", trim: true },
    notarizationRejectionReason: { type: String, default: "", trim: true },
    notarizationVerificationChecklist: { type: mongoose.Schema.Types.Mixed, default: null },
    notarizedAt: { type: Date, default: null },
    notarizationPlace: { type: String, default: "", trim: true },
    notaryName: { type: String, default: "", trim: true },
    notaryOffice: { type: String, default: "", trim: true },
    documentNumber: { type: String, default: "", trim: true },
    pageNumber: { type: String, default: "", trim: true },
    bookNumber: { type: String, default: "", trim: true },
    seriesYear: { type: Number, default: null, min: 1900, max: 2200 },
    notarizedStorageKey: { type: String, default: null },
    finalStorageKey: { type: String, default: null },
    finalDocument: { type: finalDocumentSchema, default: null },
    readyForPublicationAt: { type: Date, default: null },
    readyForPublicationBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    publishedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    publicationNotes: { type: String, default: "", trim: true },
    tenantVisible: { type: Boolean, default: false },
    isCanonical: { type: Boolean, default: true, index: true },
    publicationStatus: {
      type: String,
      enum: ["internal", "ready_for_resident", "published", "withdrawn"],
      default: undefined,
      index: true,
    },
    publicationChecklist: { type: mongoose.Schema.Types.Mixed, default: null },
    publicationChecklistConfirmedAt: { type: Date, default: null },
    publicationChecklistConfirmedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    generatedAt: { type: Date, default: null },
    signedUploadedAt: { type: Date, default: null },
    notarizedUploadedAt: { type: Date, default: null },
    publishedAt: { type: Date, default: null },

    status: { type: String, enum: CONTRACT_STATUSES, default: "draft", required: true, index: true },
    isCurrent: { type: Boolean, default: true, index: true },
    statusHistory: { type: [statusHistorySchema], default: [] },
    previousContractId: { type: mongoose.Schema.Types.ObjectId, ref: "Contract", default: null },
    renewedContractId: { type: mongoose.Schema.Types.ObjectId, ref: "Contract", default: null },
    supersededBy: { type: mongoose.Schema.Types.ObjectId, ref: "Contract", default: null },
    supersededByContractId: { type: mongoose.Schema.Types.ObjectId, ref: "Contract", default: null },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  },
  { timestamps: true },
);

contractSchema.index({ branch: 1, contractYear: 1, contractSequence: 1 }, { unique: true });
contractSchema.index({ tenantId: 1, isCurrent: 1, createdAt: -1 });
contractSchema.index({ branch: 1, status: 1, createdAt: -1 });
contractSchema.index(
  { stayId: 1 },
  { unique: true, partialFilterExpression: { stayId: { $type: "objectId" }, isCurrent: true } },
);

export default mongoose.model("Contract", contractSchema);
