import mongoose from "mongoose";
import { afterAll, beforeAll, beforeEach, describe, expect, jest, test } from "@jest/globals";
import { MongoMemoryReplSet } from "mongodb-memory-server";

await jest.unstable_mockModule("../middleware/logger.js", () => ({
  default: { info: jest.fn(), warn: jest.fn(), error: jest.fn() },
}));
await jest.unstable_mockModule("../utils/notificationService.js", () => ({
  notify: { contractDocumentReady: jest.fn().mockResolvedValue(true) },
}));
await jest.unstable_mockModule("../utils/socket.js", () => ({
  emitToUser: jest.fn(),
  emitToAdmins: jest.fn(),
}));
await jest.unstable_mockModule("./notifications/notificationService.js", () => ({
  notifyBranchAdmins: jest.fn().mockResolvedValue([]),
}));

const { Contract, Reservation, Room, User, BusinessSettings } = await import("../models/index.js");
const { createDraftContract, getContractValidation } = await import("./contractService.js");
const {
  auditContractDraftDateRecovery,
  repairContractDraftDates,
} = await import("./contractDraftRecoveryService.js");
const { autoGenerateDepositSettledContract } = await import("./autoContractOrchestratorService.js");
const { resolveTenantContractDocument } = await import("./tenantContractDocumentResolver.js");
const { removePreparedContractDocument } = await import("./contractDocumentStorageService.js");

describe("targetMoveInDate Contract generation and stuck-draft recovery", () => {
  let mongo;
  let actor;

  beforeAll(async () => {
    mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } });
    await mongoose.connect(mongo.getUri(), { dbName: "target_movein_contract_recovery" });
    await Contract.syncIndexes();
  }, 120_000);

  afterAll(async () => {
    const contracts = await Contract.find({}).lean();
    for (const contract of contracts) {
      for (const document of contract.preparedDocuments || []) {
        await removePreparedContractDocument(document).catch(() => {});
      }
    }
    await mongoose.disconnect();
    await mongo?.stop();
  }, 120_000);

  beforeEach(async () => {
    await Promise.all([
      Reservation.deleteMany({}),
      Room.deleteMany({}),
      User.deleteMany({}),
      Contract.deleteMany({}),
      BusinessSettings.deleteMany({}),
    ]);
    await BusinessSettings.create({
      key: "global",
      isDiscountEnabled: true,
      longTermLeaseMinMonths: 6,
      defaultLongTermDiscountPercent: 10,
    });
    actor = await User.create({
      firebaseUid: `actor-${new mongoose.Types.ObjectId()}`,
      username: `actor_${new mongoose.Types.ObjectId().toString().slice(-10)}`,
      email: `actor-${new mongoose.Types.ObjectId()}@example.test`,
      firstName: "Contract",
      lastName: "Reviewer",
      role: "branch_admin",
      branch: "gil-puyat",
    });
  });

  async function seedSources({ duration = 12 } = {}) {
    const tenant = await User.create({
      firebaseUid: `tenant-${new mongoose.Types.ObjectId()}`,
      username: `tenant_${new mongoose.Types.ObjectId().toString().slice(-10)}`,
      email: `tenant-${new mongoose.Types.ObjectId()}@example.test`,
      firstName: "Target",
      lastName: "Only",
      role: "applicant",
    });
    const room = await Room.create({
      name: "Private 501",
      roomNumber: "501",
      branch: "gil-puyat",
      type: "private",
      capacity: 1,
      price: 15000,
    });
    const reservation = await Reservation.create({
      userId: tenant._id,
      roomId: room._id,
      status: "reserved",
      leaseDuration: duration,
      reservationFeeAmount: 2000,
      preferredRoomType: "private",
      agreedToPrivacy: true,
      agreedToCertification: true,
      totalPrice: 15000,
      confirmedMoveInDate: null,
      moveInDate: null,
      intendedMoveInDate: null,
      targetMoveInDate: new Date("2026-08-28T00:00:00.000Z"),
      paymentStatus: "paid",
      reservationFeePaymentStatus: "verified",
      applicationReviewedAt: new Date("2026-08-20T00:00:00.000Z"),
      applicationReviewedBy: actor._id,
      approvedForPaymentAt: new Date("2026-08-20T00:00:00.000Z"),
    });
    return { tenant, room, reservation };
  }

  test.each([
    [3, "short_term", "2026-11-28T00:00:00.000Z"],
    [12, "long_term", "2027-08-28T00:00:00.000Z"],
  ])("future %i-month Contract creation consumes targetMoveInDate", async (duration, leaseType, expectedEnd) => {
    const { reservation } = await seedSources({ duration });

    const contract = await createDraftContract({
      reservationId: reservation._id,
      actorId: actor._id,
    });

    expect(contract.leaseStartDate.toISOString()).toBe("2026-08-28T00:00:00.000Z");
    expect(contract.leaseEndDate.toISOString()).toBe(expectedEnd);
    expect(contract.leaseType).toBe(leaseType);
  });

  test("reuses and repairs one canonical stuck draft, resumes generation, exposes the document, and is idempotent", async () => {
    const { tenant, room, reservation } = await seedSources({ duration: 12 });
    const draft = await Contract.create({
      tenantId: tenant._id,
      applicationId: reservation._id,
      reservationId: reservation._id,
      roomId: room._id,
      branch: room.branch,
      contractNumber: "LIL-GP-2026-09999",
      contractYear: 2026,
      contractSequence: 9999,
      version: 1,
      contractPurpose: "initial",
      initialContractKey: `reservation:${reservation._id}`,
      templateType: "private_long_term",
      roomType: "private",
      leaseType: "long_term",
      propertyName: "Lilycrest Dormitory",
      propertyAddress: "Gil Puyat, Makati City",
      roomNumber: room.roomNumber,
      tenantLegalName: "Target Only",
      tenantAddress: "123 Test Street, Makati City",
      tenantEmail: tenant.email,
      tenantPhone: "09170000000",
      tenantNationality: "Filipino",
      tenantBirthDate: new Date("2000-01-01T00:00:00.000Z"),
      leaseStartDate: null,
      leaseEndDate: null,
      leaseDurationMonths: 12,
      regularMonthlyRate: 15000,
      discountPercentage: 0,
      discountType: "none",
      discountAmount: 0,
      approvedMonthlyRate: 15000,
      advanceRentAmount: 15000,
      securityDepositAmount: 15000,
      reservationFeeAmount: 2000,
      reservationFeeCreditAmount: 2000,
      pricingApprovalId: reservation._id,
      pricingApprovedBy: actor._id,
      pricingApprovedAt: new Date("2026-08-20T00:00:00.000Z"),
      advanceCoverageStart: null,
      advanceCoverageEnd: null,
      status: "draft",
      isCurrent: true,
      statusHistory: [{ status: "draft", changedBy: actor._id, reason: "Legacy stuck draft" }],
      createdBy: actor._id,
      updatedBy: actor._id,
    });
    const before = getContractValidation(draft);
    expect(before.missingFields.map(({ field }) => field)).toEqual(expect.arrayContaining([
      "leaseStartDate", "leaseEndDate", "advanceCoverageStart", "advanceCoverageEnd",
    ]));

    const audit = await auditContractDraftDateRecovery();
    expect(audit).toMatchObject({ matchingCandidates: 1, safeCandidates: 1, ambiguous: 0 });

    const lifecycle = await autoGenerateDepositSettledContract({
      reservationId: reservation._id,
      actorId: actor._id,
    });
    expect(lifecycle.success).toBe(true);

    const generated = await Contract.findById(draft._id);
    expect(await Contract.countDocuments({ reservationId: reservation._id })).toBe(1);
    expect(generated.leaseStartDate.toISOString()).toBe("2026-08-28T00:00:00.000Z");
    expect(generated.leaseEndDate.toISOString()).toBe("2027-08-28T00:00:00.000Z");
    expect(generated.status).toBe("generated");
    expect(getContractValidation(generated).missingFields.map(({ field }) => field)).not.toEqual(
      expect.arrayContaining(["leaseStartDate", "leaseEndDate"]),
    );
    expect(resolveTenantContractDocument(generated)).toMatchObject({
      available: true,
      type: "generated_draft",
      version: 1,
    });

    const version = generated.generatedVersion;
    const updatedAt = generated.updatedAt.getTime();
    const secondRepair = await repairContractDraftDates({
      contractId: draft._id,
      actorId: actor._id,
    });
    const secondLifecycle = await autoGenerateDepositSettledContract({
      reservationId: reservation._id,
      actorId: actor._id,
    });
    const unchanged = await Contract.findById(draft._id);
    expect(secondRepair.mutations).toBe(0);
    expect(secondLifecycle).toMatchObject({ success: true, status: "generated" });
    expect(unchanged.generatedVersion).toBe(version);
    expect(unchanged.preparedDocuments).toHaveLength(1);
    expect(unchanged.updatedAt.getTime()).toBe(updatedAt);
  }, 30_000);
});
