/**
 * Integration test for the reservation-settlement → draft Contract gate.
 *
 * AUTHORITATIVE RULE: A Reservation is not yet a Contract. Contract
 * generation must only happen once BOTH required payment gates are
 * satisfied:
 *   1. Reservation Fee = PAID
 *   2. Advance + Security Deposit = PAID
 *
 * For structured-workflow reservations (financialWorkflowVersion ===
 * "structured-initial-payment-v1"), settleReservationDeposit only confirms
 * gate 1 — it must NOT create a Contract. Gate 2 is a separate
 * "initial_payment" Bill reaching ₱0 remaining, at which point
 * autoGenerateDepositSettledContract (via
 * structuredInitialPaymentService.syncStructuredReservationAfterBillSettlement)
 * is the sole, correct trigger.
 *
 * Legacy (pre-structured-workflow) reservations have no second payment step
 * at all — settleReservationDeposit remains their sole and immediate
 * trigger, preserving prior behavior rather than leaving them permanently
 * stuck with no path to a Contract.
 *
 * Uses a real (single-node) replica set via MongoMemoryReplSet because
 * settleReservationDeposit runs inside a genuine Mongo transaction
 * (mongoSession.withTransaction), which a standalone MongoMemoryServer
 * cannot support.
 */
import mongoose from "mongoose";
import { afterAll, beforeAll, beforeEach, describe, expect, test } from "@jest/globals";
import { MongoMemoryReplSet } from "mongodb-memory-server";

import { settleReservationDeposit } from "./reservationDepositSettlementService.js";
import { syncStructuredReservationAfterBillSettlement } from "./structuredInitialPaymentService.js";
import { createDraftContract } from "./contractService.js";
import { Contract, Payment, Reservation, Room, User, Bill, BusinessSettings } from "../models/index.js";

describe("reservation deposit settlement -> draft Contract gate (both payments required)", () => {
  let mongo;

  beforeAll(async () => {
    mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 } });
    await mongoose.connect(mongo.getUri(), { dbName: "settlement_contract_automation" });
    // Only sync indexes actually load-bearing for these assertions —
    // Reservation's full index set includes a partial-filter spec this
    // memory-server's mongod build rejects and is unrelated to what's
    // being tested here (Contract's own uniqueness guarantees are what
    // matter for the duplicate/race assertions below).
    await Contract.syncIndexes();
  }, 120_000);

  afterAll(async () => {
    await mongoose.disconnect();
    await mongo?.stop();
  }, 120_000);

  beforeEach(async () => {
    await Promise.all([
      Reservation.deleteMany({}),
      Room.deleteMany({}),
      User.deleteMany({}),
      Contract.deleteMany({}),
      Payment.deleteMany({}),
      Bill.deleteMany({}),
      BusinessSettings.deleteMany({}),
    ]);
    await BusinessSettings.create({
      key: "global",
      quadrupleDiscountPercent: 10,
      isDiscountEnabled: true,
      longTermLeaseMinMonths: 6,
    });
  });

  async function seedTenantRoomReservation({
    leaseDuration = 12,
    status = "approved_for_payment",
    targetMoveInOnly = false,
    structured = false,
  } = {}) {
    const tenant = await User.create({
      firebaseUid: `firebase-${new mongoose.Types.ObjectId()}`,
      email: `tenant-${new mongoose.Types.ObjectId()}@example.test`,
      username: `tenant_${new mongoose.Types.ObjectId().toString().slice(-10)}`,
      firstName: "Test",
      lastName: "Tenant",
      role: "applicant",
    });
    const room = await Room.create({
      name: "Room 301",
      roomNumber: "301",
      branch: "gil-puyat",
      type: "quadruple-sharing",
      capacity: 4,
      price: 6300,
    });
    const reservation = await Reservation.create({
      userId: tenant._id,
      roomId: room._id,
      status,
      leaseDuration,
      reservationFeeAmount: 2000,
      preferredRoomType: "quadruple-sharing",
      agreedToPrivacy: true,
      agreedToCertification: true,
      totalPrice: 6300,
      moveInDate: targetMoveInOnly ? null : new Date("2026-09-01T00:00:00.000Z"),
      targetMoveInDate: targetMoveInOnly ? new Date("2026-09-01T00:00:00.000Z") : null,
      ...(structured ? { financialWorkflowVersion: "structured-initial-payment-v1" } : {}),
    });
    return { tenant, room, reservation };
  }

  function settleFor(reservation, overrides = {}) {
    return settleReservationDeposit({
      reservationId: reservation._id,
      source: "manual_proof",
      paidAmount: 2000,
      idempotencyKey: `settle-${reservation._id}`,
      actor: { role: "branch_admin" },
      ...overrides,
    });
  }

  // Simulates the Advance + Security Deposit gate being fully paid, the same
  // way paymentController.js / webhookController.js drive it in production:
  // an "initial_payment" Bill reaching paidAmount === totalAmount, then
  // syncStructuredReservationAfterBillSettlement runs (which itself calls
  // autoGenerateDepositSettledContract once remaining === 0).
  async function payAdvanceAndDeposit(reservation, room, { amount = 10800 } = {}) {
    const bill = await Bill.create({
      reservationId: reservation._id,
      userId: reservation.userId,
      branch: room.branch,
      billType: "initial_payment",
      structuredWorkflowVersion: "structured-initial-payment-v1",
      totalAmount: amount,
      paidAmount: amount,
      status: "paid",
      billingMonth: "2026-09",
      dueDate: new Date("2026-09-01T00:00:00.000Z"),
    });
    await syncStructuredReservationAfterBillSettlement(bill);
    return bill;
  }

  // ── Test A: neither gate paid ────────────────────────────────────────────
  test("A: Reservation Fee unpaid, Advance+Deposit unpaid -> Contract count = 0", async () => {
    const { reservation } = await seedTenantRoomReservation({ structured: true });
    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(0);
  });

  // ── Test B: only Reservation Fee paid (structured workflow) ─────────────
  test("B: Reservation Fee PAID, Advance+Deposit unpaid -> Contract count = 0", async () => {
    const { reservation } = await seedTenantRoomReservation({ structured: true });

    const result = await settleFor(reservation);

    expect(result.settled).toBe(true);
    expect(result.reservation.status).toBe("reserved");
    expect(result.draftContract).toBeUndefined();

    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(0);
  });

  // ── Test D: both gates paid ───────────────────────────────────────────────
  test("D: Reservation Fee PAID, Advance+Deposit PAID -> Contract automatically generated exactly once", async () => {
    const { reservation, room, tenant } = await seedTenantRoomReservation({ structured: true });

    await settleFor(reservation);
    let contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(0);

    await payAdvanceAndDeposit(reservation, room);

    contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
    expect(contracts[0].status).toBe("draft");
    expect(String(contracts[0].tenantId)).toBe(String(tenant._id));
  });

  // ── Test E: cancel before both gates satisfied ────────────────────────────
  test("E: Reservation Fee PAID, Advance+Deposit unpaid, tenant cancels -> Reservation cancelled, Contract count = 0, inventory released", async () => {
    const { reservation, room } = await seedTenantRoomReservation({ structured: true });
    await settleFor(reservation);

    const settled = await Reservation.findById(reservation._id);
    expect(settled.status).toBe("reserved");

    settled.status = "cancelled";
    settled.cancelledAt = new Date();
    settled.cancellationSource = "applicant";
    settled.cancellationReason = "Plans changed";
    await settled.save();

    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(0);

    const cancelled = await Reservation.findById(reservation._id).lean();
    expect(cancelled.status).toBe("cancelled");
    void room;
  });

  // ── Test F: duplicate reconciliation after both gates paid ───────────────
  test("F: both PAID, Contract generated, duplicate reconciliation event -> no duplicate Contract", async () => {
    const { reservation, room } = await seedTenantRoomReservation({ structured: true });
    await settleFor(reservation);
    await payAdvanceAndDeposit(reservation, room);

    let contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
    const firstContractId = String(contracts[0]._id);

    // Duplicate settlement event for the same already-paid bill.
    const bill = await Bill.findOne({ reservationId: reservation._id, billType: "initial_payment" });
    await syncStructuredReservationAfterBillSettlement(bill);

    contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
    expect(String(contracts[0]._id)).toBe(firstContractId);
  });

  // ── Test G: cancelled reservation, background job runs ───────────────────
  test("G: Reservation cancelled before both gates paid, background Contract-generation job runs -> no Contract generated", async () => {
    const { reservation, room } = await seedTenantRoomReservation({ structured: true });
    await settleFor(reservation);

    const settled = await Reservation.findById(reservation._id);
    settled.status = "cancelled";
    settled.cancelledAt = new Date();
    settled.cancellationReason = "Plans changed";
    await settled.save();

    // The job (Job 19 / reconcileMissingContractGeneration) only scans
    // EXISTING stuck Contracts — since none exists (gate 2 was never
    // reached), there is nothing for it to act on. Directly assert the
    // invariant it must never violate: no Contract materializes later.
    const { resolveReservationContractEligibility } = await import(
      "./reservationContractEligibilityService.js"
    );
    const cancelledReservation = await Reservation.findById(reservation._id).lean();
    const eligibility = resolveReservationContractEligibility(cancelledReservation, {
      tenantExists: true,
      roomExists: true,
      roomType: room.type,
      bedExists: false,
    });
    expect(eligibility.eligible).toBe(false);
    expect(eligibility.approvalState).toBe("inconsistent");

    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(0);
  });

  // ── Test H: active tenancy blocks cancellation (P1, unaffected) ──────────
  test("H: active Stay exists, cancel Reservation requested -> blocked, use Move-Out/Termination", async () => {
    const { reservation, tenant } = await seedTenantRoomReservation({ structured: true, status: "moveIn" });
    const { Stay } = await import("../models/index.js");
    await Stay.create({
      tenantId: tenant._id,
      reservationId: reservation._id,
      branch: "gil-puyat",
      roomId: reservation.roomId,
      bedId: "bed-1",
      leaseStartDate: new Date("2026-09-01T00:00:00.000Z"),
      leaseEndDate: new Date("2027-09-01T00:00:00.000Z"),
      status: "active",
    });

    const { assertNoActiveStayOrProgressedContract } = await import(
      "../controllers/reservations/_helpers.js"
    );
    await expect(
      assertNoActiveStayOrProgressedContract(reservation._id, tenant._id),
    ).rejects.toMatchObject({ code: "ACTIVE_STAY_OR_CONTRACT_BLOCKS_CANCELLATION", statusCode: 409 });
  });

  // ── Legacy-workflow preservation ──────────────────────────────────────────
  test("legacy (non-structured) reservations still get an immediate draft Contract on settlement (unchanged prior behavior)", async () => {
    const { reservation, tenant, room } = await seedTenantRoomReservation({ structured: false });

    const result = await settleFor(reservation);

    expect(result.settled).toBe(true);
    expect(result.draftContract).toBeTruthy();
    expect(result.draftContract.status).toBe("draft");
    expect(String(result.draftContract.tenantId)).toBe(String(tenant._id));

    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
    void room;
  });

  test("legacy: calling settlement twice with the same idempotency key does not create a second Contract", async () => {
    const { reservation } = await seedTenantRoomReservation({ structured: false });
    const idempotencyKey = `dup-key-${reservation._id}`;

    const first = await settleFor(reservation, { idempotencyKey });
    const second = await settleFor(reservation, { idempotencyKey });

    expect(first.draftContract).toBeTruthy();
    expect(second.idempotent).toBe(true);
    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
  });

  test("legacy: simultaneous settlement attempts (race) still produce exactly one Contract", async () => {
    const { reservation } = await seedTenantRoomReservation({ structured: false });

    const [a, b] = await Promise.allSettled([
      settleFor(reservation, { idempotencyKey: "race-a" }),
      settleFor(reservation, { idempotencyKey: "race-b" }),
    ]);

    expect([a.status, b.status]).toContain("fulfilled");
    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
  });

  test("legacy: a reservation that already has a Contract (manual pre-creation) is not duplicated by settlement", async () => {
    const { reservation, tenant, room } = await seedTenantRoomReservation({ structured: false });
    const manual = await createDraftContract({ reservationId: reservation._id, actorId: tenant._id });

    const result = await settleFor(reservation);

    expect(String(result.draftContract._id)).toBe(String(manual._id));
    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(1);
    expect(String(contracts[0]._id)).toBe(String(manual._id));
    void room;
  });

  test("legacy: mobile-relevant — the created draft Contract is immediately eligible for mobile visibility (includeEarlyStages)", async () => {
    const { reservation, tenant } = await seedTenantRoomReservation({ structured: false });
    const result = await settleFor(reservation);

    const { resolveTenantCanonicalContract } = await import("./tenantContractSelectionService.js");
    const mobileVisible = await resolveTenantCanonicalContract(tenant._id, { includeEarlyStages: true });
    expect(String(mobileVisible?._id)).toBe(String(result.draftContract._id));
    expect(mobileVisible.status).toBe("draft");

    const webVisible = await resolveTenantCanonicalContract(tenant._id);
    expect(webVisible).toBeNull(); // unchanged Web "My Contract" behavior — draft still hidden there
  });

  test("legacy: settlement still succeeds and the reservation is not left partially inconsistent even if Contract creation is impossible", async () => {
    // A Stay already linked to this reservation but recorded under a
    // different (still schema-valid) branch than the room itself —
    // createDraftContract's stay-vs-room branch-conflict guard throws
    // CONTRACT_BRANCH_CONFLICT deterministically. This is the schema-valid
    // way to force Contract creation to fail without touching any of
    // settlement's own preconditions (tenant/room/payment all still valid).
    const { Stay } = await import("../models/index.js");
    const { tenant, room, reservation } = await seedTenantRoomReservation({ structured: false });
    await Stay.create({
      tenantId: tenant._id,
      reservationId: reservation._id,
      branch: "guadalupe", // conflicts with room.branch === "gil-puyat"
      roomId: room._id,
      bedId: "bed-1",
      leaseStartDate: new Date("2026-09-01T00:00:00.000Z"),
      leaseEndDate: new Date("2027-09-01T00:00:00.000Z"),
      status: "active",
    });

    const result = await settleFor(reservation);

    // Payment settlement is authoritative and must not roll back just
    // because Contract drafting failed downstream.
    expect(result.settled).toBe(true);
    const updatedReservation = await Reservation.findById(reservation._id).lean();
    expect(updatedReservation.status).toBe("reserved");
    expect(updatedReservation.paymentStatus).toBe("paid");
    const contracts = await Contract.find({ reservationId: reservation._id });
    expect(contracts).toHaveLength(0);
  });
});
